version: '3.9'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./videos:/app/videos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - server
volumes:
  mongo-data:
