version: '3.9'
services:
  server:
    command: npm run dev
    volumes:
      - ./server:/app
      - ./videos:/app/videos
    ports:
      - "4000:4000"
  client:
    command: npm start
    volumes:
      - ./client:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
