name: Docker CI

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKERHUB_USER }}/my-goal-video-app:latest

      - name: Scan image
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: ${{ steps.build.outputs.imageid }}
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true
